### ISSUE TITLE
Top-Meritページ　文字の太さをboldに

### ISSUE THREAD

**Issue by kogachan4** [lec-cafe/leccafe_site#52]
”詳しく知りたい方は まずは資料請求！”のfont-weightをboldにしてください。

![スクリーンショット 2020-03-16 17 46 56](https://user-images.githubusercontent.com/55970295/76738568-3dfa3680-67ae-11ea-844e-ab509c99aba8.png)

**Comment by shunking-tech** [comment]
boldになっているはずです！
