### ISSUE TITLE
アップルタッチアイコン設定

### ISSUE THREAD

**Issue by yasui05821** [lec-cafe/leccafe_site#96]
アップルタッチアイコン　→　#95

- [ ] アップルタッチアイコンのファイルアップロード
- [ ] コードの設定
- [ ] 実装確認

**Comment by shunking-tech** [comment]
↑チェック入れられなかったので作りました

- [ ] アップルタッチアイコンのファイルアップロード

- [ ] コードの設定

- [ ] 実装確認
