### ISSUE TITLE
OGP画像の準備

### ISSUE THREAD

**Issue by yasui05821** [lec-cafe/leccafe_site#99]

**Comment by NaNagaiShiho** [comment]
![ogp – 1](https://user-images.githubusercontent.com/58157082/77295099-a7d38c80-6d28-11ea-8a86-2fb834cb676f.png)
![ogp – 2](https://user-images.githubusercontent.com/58157082/77295110-ac984080-6d28-11ea-8b96-c8699ee46738.png)
![ogp](https://user-images.githubusercontent.com/58157082/77295111-ad30d700-6d28-11ea-9fc4-d43f26189b08.png)
![ogp – 3](https://user-images.githubusercontent.com/58157082/77295126-b326b800-6d28-11ea-9c49-944787117108.png)
![ogp – 4](https://user-images.githubusercontent.com/58157082/77295130-b621a880-6d28-11ea-9053-7fe095eca135.png)

**Comment by NaNagaiShiho** [comment]
![ogp – 5](https://user-images.githubusercontent.com/58157082/77295336-19133f80-6d29-11ea-8cdf-d3a12ab98af6.png)
![ogp – 6](https://user-images.githubusercontent.com/58157082/77295604-9e96ef80-6d29-11ea-8ab1-7f6f6d41a335.png)

**Comment by NaNagaiShiho** [comment]
![ogp – 8](https://user-images.githubusercontent.com/58157082/77300131-e3725480-6d30-11ea-9574-8bf9912a7a9d.png)
